apiVersion: v1
data:
  nginx.conf: |-
    server {
      listen 80;
      location / {
        proxy_pass http:$GO-SERVICE//:8080;
      }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: proxy
  name: proxy-cm0